package com.martinkorelic.mobiletransformers.agent

import com.martinkorelic.mobiletransformers.MobileActionsPreprocessor
import java.io.File
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

/**
 * #37 cross-language parity: **every training target the Python importer emits is a call this
 * validator accepts.**
 *
 * This is the property the whole tool-call design rests on. `mobiletransformers agent-dataset` writes
 * the training rows and the action schema from one corpus in one command; if the two could disagree,
 * a model that learned the data perfectly would still be refused at the boundary, and the failure
 * would only appear after an export → push → long device run.
 *
 * Both fixtures are generated by that command from
 * `tests/fixtures/agent/mobile_actions_sample.jsonl` (excerpted from `google/mobile-actions`,
 * CC-BY-4.0) and read here from the repo root — the same shared-oracle pattern `PackagesTest` uses,
 * so Kotlin and Python cannot drift.
 *
 * Robolectric for the same reason `FileUtilParseTest` needs it: `org.json.JSONObject` and
 * `android.content.Intent` are real framework classes that the plain unit-test classpath stubs, and
 * `isReturnDefaultValues = false` makes those stubs throw rather than quietly return null.
 */
@RunWith(RobolectricTestRunner::class)
class MobileActionsParityTest {

    private fun repoRoot(): File {
        var dir: File? = File("").absoluteFile
        while (dir != null) {
            if (File(dir, "tests/fixtures/agent/expected_action_schema.json").isFile) return dir
            dir = dir.parentFile
        }
        error("could not locate repo root from ${File("").absolutePath}")
    }

    private fun fixtures() = File(repoRoot(), "tests/fixtures/agent")
    private fun validator() = FunctionCallValidator.fromSchema(File(fixtures(), "expected_action_schema.json"))
    private fun rows(): List<JSONObject> =
        File(fixtures(), "expected_rows.jsonl").readLines()
            .filter { it.isNotBlank() }
            .map { JSONObject(it) }

    @Test
    fun everyEmittedCompletionIsAcceptedByTheValidator() {
        val validator = validator()
        val rows = rows()
        assertTrue("fixture carries no rows", rows.isNotEmpty())

        for (row in rows) {
            val completion = row.getString("completion")
            // Throws RejectedCallException on any disagreement, naming the offending entity.
            val call = validator.validate(completion)
            assertTrue(
                "accepted call names an action outside the schema",
                call.actionName in validator.allowedActions,
            )
        }
    }

    @Test
    fun acceptedCallsCarryOnlyIntentsTheSchemaDeclared() {
        val validator = validator()
        val declared = FunctionCallValidator
            .fromSchema(File(fixtures(), "expected_action_schema.json"))
            .allowedActions

        for (row in rows()) {
            val call = validator.validate(row.getString("completion"))
            assertTrue(call.actionName in declared)
            // An action with no mapped Android intent is trainable and validatable but NEVER bindable;
            // the importer leaves `allowedIntent` empty rather than inventing one.
            if (call.allowedIntent.isNotEmpty()) {
                val intended = IntentBinder.dryRun(call)
                assertEquals(call.allowedIntent, intended.intent.action)
                assertTrue("dry-run must never mark itself executable", !intended.willExecute)
            }
        }
    }

    @Test
    fun theCuratorReadsTheEmittedRowShape() {
        // The bridge that did not exist until 2026-08-14: without a preprocessor registered for this
        // schema, `ORTDataCurator` drops every row and trains on nothing while reporting success.
        for (row in rows()) {
            val (input, label) = MobileActionsPreprocessor.preprocess(row)
            assertTrue("prompt must not be blank", input.isNotBlank())
            assertTrue("completion must not be blank", label.isNotBlank())
            // The label IS the tool call — not a prose rendering of it.
            assertEquals(row.getString("completion"), label)
        }
    }

    @Test
    fun aCallNamingAnActionOutsideTheCorpusIsStillRejected() {
        // The schema is derived from data, which must not make it permissive.
        val error = org.junit.Assert.assertThrows(RejectedCallException::class.java) {
            validator().validate("""{"actionName": "wipe_device", "parameters": {}}""")
        }
        assertTrue(error.message!!.contains("not allowlisted"))
    }
}
