package com.martinkorelic.mobiletransformers.federated

import com.martinkorelic.mobiletransformers.packages.WeightHandoffMap
import java.nio.ByteBuffer
import java.nio.ByteOrder
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * #36 DoD: the Kotlin codec is **byte-identical** to Python's, proven against the checked-in golden.
 *
 * `tests/federated/fixtures/federated_record.golden.bin` is copied into this module's test resources
 * (Gradle cannot reach the Python fixture tree), together with a JSON rendering of the same synthetic
 * `HandoffMap` the golden was generated from. Both are regenerated by
 * `python -m tests.federated.gen_serialization_golden`; if these bytes and Python's ever disagree, the
 * Kotlin side is wrong by definition — it is a mirror, not a second implementation.
 *
 * The golden is 1020 bytes: 4 (header length) + 872 (header) + 144 (payload).
 */
class AdapterTensorCodecTest {

    private fun resource(name: String): ByteArray =
        checkNotNull(javaClass.classLoader.getResourceAsStream(name)) { "missing test resource $name" }
            .use { it.readBytes() }

    private fun handoff(): WeightHandoffMap =
        WeightHandoffMap.parse(String(resource("federated_handoff.json"), Charsets.UTF_8))

    /** `np.arange(n, dtype=float32)` as little-endian bytes — what the fixture builder writes. */
    private fun arange(count: Int): ByteArray {
        val buf = ByteBuffer.allocate(count * 4).order(ByteOrder.LITTLE_ENDIAN)
        for (i in 0 until count) buf.putFloat(i.toFloat())
        return buf.array()
    }

    private fun deterministicRecord(): FederatedRecord = AdapterTensorCodec.build(
        handoff = handoff(),
        baseModelId = "org/base",
        packageRevision = "rev-1",
        peftMethod = "lora",
        round = 0,
    ) { spec -> arange(spec.elementCount.toInt()) }

    @Test
    fun serializationIsByteIdenticalToThePythonGolden() {
        val golden = resource("federated_record.golden.bin")

        val ours = AdapterTensorCodec.serialize(deterministicRecord())

        assertEquals("record length differs from the golden", golden.size, ours.size)
        assertArrayEquals(
            "Kotlin serialization diverged from Python's. The header is built by hand because " +
                "json.dumps uses ', ' / ': ' separators and recursive key sorting that Gson does not " +
                "reproduce — check those first.",
            golden,
            ours,
        )
    }

    @Test
    fun theGoldenDeserializesToTheExpectedTensorIdentities() {
        val record = AdapterTensorCodec.deserialize(resource("federated_record.golden.bin"))

        // Codec order: entries by canonical weight name, each expanded by ADAPTER_ROLE_ORDER.
        assertEquals(
            listOf(
                "l0.lora_A.lora.weight",
                "l0.lora_B.lora.weight",
                "l1.lora_A.lora.weight",
                "l1.lora_B.lora.weight",
            ),
            record.tensors.map { it.name },
        )
        assertEquals(
            listOf("adapter_A", "adapter_B", "adapter_A", "adapter_B"),
            record.tensors.map { it.role },
        )
        // Shapes are read from the map, NOT inferred from the rank — that inference is the
        // re-derivation that causes layer-identity defects.
        assertEquals(listOf(2L, 3L), record.tensors[0].shape)
        assertEquals(listOf(6L, 2L), record.tensors[3].shape)
        assertEquals("1.1", record.adapterFormatVersion)
    }

    @Test
    fun roundTripsThroughItsOwnSerialization() {
        val record = deterministicRecord()

        val decoded = AdapterTensorCodec.deserialize(AdapterTensorCodec.serialize(record))

        assertEquals(record.tensors, decoded.tensors)
        assertEquals(record.baseModelId, decoded.baseModelId)
        assertEquals(record.round, decoded.round)
    }

    @Test
    fun aPreSchema11PackageFailsClosedNamingTheReExport() {
        // Intended behaviour, explicitly NOT a fallback to merged weights: a 1.0 map cannot describe
        // the rank-r factors at all, and guessing them from the rank is what this design rejects.
        val old = WeightHandoffMap.parse(
            """{"schemaVersion": "1.0", "minReaderVersion": "1.0", "entries": [
                 {"trainingBaseLayerName": "l0", "dtype": "float32", "shape": [4, 3]}]}"""
        )

        val error = assertThrows(Exception::class.java) { old.adapterTensorSpecs() }
        assertTrue(
            "the message must tell the reader to re-export, not just that something is missing: " +
                "'${error.message}'",
            error.message!!.contains("re-export", ignoreCase = true),
        )
    }

    @Test
    fun aTensorWhoseBytesDoNotMatchItsDeclaredShapeIsRejected() {
        val error = assertThrows(FederatedRecordException::class.java) {
            AdapterTensorCodec.build(handoff(), "org/base", "rev-1", "lora", 0) { arange(1) }
        }
        assertTrue(error.message!!.contains("bytes"))
    }

    @Test
    fun aMissingFactorIsNamedRatherThanSilentlySkipped() {
        // Matching by NAME is the point: the Python simulation had a defect where tensors were paired
        // by checkpoint ITERATION order, which would write one layer's lora_A over another's.
        val error = assertThrows(FederatedRecordException::class.java) {
            AdapterTensorCodec.build(handoff(), "org/base", "rev-1", "lora", 0) { spec ->
                if (spec.name.startsWith("l1.")) null else arange(spec.elementCount.toInt())
            }
        }
        assertTrue(error.message!!.contains("l1."))
    }

    @Test
    fun aTruncatedRecordIsRejectedRatherThanPartiallyRead() {
        val golden = resource("federated_record.golden.bin")

        for (cut in listOf(2, 100, golden.size - 10)) {
            assertThrows(
                "a record truncated to $cut bytes must be rejected",
                FederatedRecordException::class.java,
            ) { AdapterTensorCodec.deserialize(golden.copyOfRange(0, cut)) }
        }
    }

    @Test
    fun aRecordFromANewerMajorSchemaIsRefusedBeforeAnyOffsetIsTrusted() {
        val record = deterministicRecord().copy(schemaVersion = "2.0", minReaderVersion = "2.0")

        val error = assertThrows(FederatedRecordException::class.java) {
            AdapterTensorCodec.deserialize(AdapterTensorCodec.serialize(record))
        }
        assertTrue(error.message!!.contains("newer"))
    }

    @Test
    fun anAdapterFormatVersionThatDisagreesWithThePackageIsRejected() {
        val record = deterministicRecord().copy(adapterFormatVersion = "1.0")

        val error = assertThrows(FederatedRecordException::class.java) {
            AdapterTensorCodec.checkFormat(record, handoff())
        }
        assertTrue(error.message!!.contains("adapterFormatVersion"))
    }

    @Test
    fun mergedRolesStayReadableEvenThoughNothingProducesThem() {
        // A peer may hold an older record; rejecting it as "unknown role" is worse than accepting it.
        for (role in listOf("weight", "weight_quantized", "scale", "zero_point")) {
            assertTrue(role in AdapterTensorCodec.SUPPORTED_ROLES)
        }
    }

    @Test
    fun onlyAdapterFactorsLeaveTheDevice() {
        // #36 DoD: "only adapter/trainable tensors leave the device". The record's vocabulary is the
        // rank-r factors; no merged base weight is ever emitted.
        val record = deterministicRecord()

        assertTrue(record.tensors.all { it.role in listOf("adapter_A", "adapter_B", "shared_A", "intermediate") })
        // Payload is 144 bytes here; the merged weights of the same two layers would be far larger.
        assertEquals(144, record.tensors.sumOf { it.payload.size })
    }
}
